repos:
    - repo: https://github.com/python/black
      rev: 22.3.0
      hooks:
          - id: black
            files: "dxcint.*"
    - repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            args: ["--config=dxcint/.flake8"]
            files: "dxcint.*"